# Generated by Django 5.2.5 on 2025-08-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='coffee',
        ),
    ]
