# Generated by Django 5.2.5 on 2025-08-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_rename_product_cartitem_coffee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='coffee',
            new_name='product',
        ),
    ]
