# Generated by Django 5.2.5 on 2025-08-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_rename_coffee_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.ImageField(upload_to='coffee/'),
        ),
    ]
