# Generated by Django 5.2.5 on 2025-08-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_alter_coffee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Quantity',
        ),
        migrations.AddField(
            model_name='coffee',
            name='category',
            field=models.CharField(choices=[('hot', 'Hot Coffee'), ('cold', 'Cold Coffee'), ('special', 'Special Coffee')], default='hot', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
